import mlflow
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

class TreeModelDiagnostics:
    def __init__(self, metric, preprocessor=None, feature_names=None, needs_proba=False, target_class_idx=1):
        """
        Initializes the diagnostics engine.
        :param metric: The scoring metric function (e.g., balanced_accuracy_score)
        :param preprocessor: The fitted ColumnTransformer/Pipeline (if any)
        :param feature_names: List of raw feature names (used if no preprocessor is provided)
        """
        self.metric = metric
        self.preprocessor = preprocessor
        self.feature_names = feature_names
        self.needs_proba = needs_proba
        self.proba_class_idx = target_class_idx

    def log_oob_score(self, estimator, fold_idx=1):
        """Safely logs OOB score if the model supports it."""
        if hasattr(estimator, "oob_score_"):
            oob = estimator.oob_score_
            mlflow.log_metric("fold_oob_score", oob, step=fold_idx)
            print(f"Fold {fold_idx} OOB Score: {oob}")

    def plot_feature_importances(self, pipeline, fold_idx=1):
        """Generates and logs feature importance plot as an artifact."""
        estimator = pipeline.named_steps['pred_model']
        
        if hasattr(estimator, "feature_importances_"):
            # Get the exact column names generated by the preprocessor
            if self.preprocessor:
                cols = self.preprocessor.get_feature_names_out()
            elif self.feature_names is not None:
                cols = self.feature_names
            else:
                raise ValueError("Either preprocessor or feature_names must be provided.")

            fi = pd.DataFrame({'cols': cols, 'imp': estimator.feature_importances_})
            fi = fi.sort_values('imp', ascending=False).head(30) # Top 30

            plt.figure(figsize=(10, 6))
            plt.barh(fi['cols'], fi['imp'], color='teal')
            plt.gca().invert_yaxis()
            plt.title(f"Feature Importance - Fold {fold_idx}")
            
            # Save and log to MLflow
            plot_path = f"feature_importance_fold_{fold_idx}.png"
            plt.savefig(plot_path, bbox_inches='tight')
            plt.close()
            mlflow.log_artifact(plot_path)

    def plot_score_vs_trees(self, pipeline, x_valid, y_valid, fold_idx=1):
        """Calculates cumulative score as trees increase for Random Forest."""
        estimator = pipeline.named_steps['pred_model']
        
        if hasattr(estimator, "estimators_"):
            # Transform the validation data first so the raw trees can read it
            if self.preprocessor:
                x_valid_transformed = self.preprocessor.transform(x_valid)
            else:
                x_valid_transformed = x_valid
            
            # Calculate cumulative mean prediction and score it
            scores = []
            
            if self.needs_proba:
                tree_preds = np.array([tree.predict_proba(x_valid_transformed) for tree in estimator.estimators_])
                
                for i in range(1, len(tree_preds) + 1):
                    cumulative_prob = tree_preds[:i].mean(axis=0) 
                    
                    if self.proba_class_idx is not None:
                        cumulative_prob = cumulative_prob[:, self.proba_class_idx]
                        
                    score = self.metric(y_valid, cumulative_prob)
                    scores.append(score)
            else:
                tree_preds = np.array([tree.predict(x_valid_transformed) for tree in estimator.estimators_])
                
                for i in range(1, len(tree_preds) + 1):
                    cumulative_pred = np.round(tree_preds[:i].mean(axis=0)) 
                    score = self.metric(y_valid, cumulative_pred)
                    scores.append(score)

            plt.figure(figsize=(8, 4))
            plt.plot(range(1, len(scores) + 1), scores, color='blue')
            plt.title(f"Score vs Number of Trees - Fold {fold_idx}")
            plt.xlabel("Number of Trees")
            plt.ylabel("Validation Score")
            
            plot_path = f"score_vs_trees_fold_{fold_idx}.png"
            plt.savefig(plot_path, bbox_inches='tight')
            plt.close()
            mlflow.log_artifact(plot_path)

    def plot_tree_depth_distribution(self, pipeline, fold_idx=1):
        """Generates and logs tree depth distribution plot for the model."""
        estimator = pipeline.named_steps['pred_model']

        if hasattr(estimator, "estimators_"):
            depths = [tree.get_depth() for tree in estimator.estimators_]

            plt.figure(figsize=(8, 4))
            plt.hist(depths, bins=20, color='green', edgecolor='black')
            plt.title(f"Tree Depth Distribution - Fold {fold_idx}")
            plt.xlabel("Tree Depth")
            plt.ylabel("Count")

            plot_path = f"tree_depth_distribution_fold_{fold_idx}.png"
            plt.savefig(plot_path, bbox_inches='tight')
            plt.close()
            mlflow.log_artifact(plot_path)

    